# Dependencies
markdown:         kramdown
kramdown:
  extensions: [tables, with_toc_data]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dennis Felsing
#tagline:          aka def- & deen
url:              http://felsin9.de/nnis/
#paginate:         1
baseurl:          /nnis/
author:
  name:           Dennis Felsing
  url:            http://felsin9.de/nnis
  email:          dennis@felsin9.de

pages_list:
  Blog: 'https://hookrace.net/'
  DDNet: 'https://ddnet.org/'
  Software: '/nnis/software/'
  Research: '/nnis/research/'
  Teaching: '/nnis/teaching/'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
