# Dependencies
markdown:         kramdown
kramdown:
  extensions: [tables, with_toc_data]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dennis Felsing
#tagline:          aka def- & deen
url:              https://dennis.felsing.org
#paginate:         1
baseurl:          /
author:
  name:           Dennis Felsing
  url:            https://dennis.felsing.org
  email:          dennis@felsing.org

pages_list:
  Blog: 'https://hookrace.net/'
  DDNet: 'https://ddnet.org/'
  Software: '/software'
  Research: '/research'
  Teaching: '/teaching'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
